/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"

/*
 * SysTick_Handler interrupt handler
 */
int SysTick_TASK = 0;
void SysTick_Handler(void)
{
	// Do stuff
	SysTick_TASK = 1;
}

int main(void)
{
	// Set Bit 4 to enable GPIOC clock
	RCC->APB2ENR |= (1 << 4);

    // Configura os pinos PC13, PC14, PC15 como saída push-pull
	GPIOC->CRH &= ~((0xF << 20) | (0xF << 24) | (0xF << 28));
	GPIOC->CRH |= (0x2 << 20) | (0x2 << 24) | (0x2 << 28);

	// Reset GPIOC Pin13, 14, 15
	GPIOC->ODR &= ~((1 << 13) | (1 << 14) | (1 << 15));

	/*System Tick Configuration
	 * Initializes the System Timer and its interrupt, and starts the System Tick Timer.
     * Counter is in free running mode to generate periodic interrupts.
	 */
	uint32_t ticks = 1000000; //ticks  Number of ticks between two interrupts, should be less than 0xFFFFFFUL = 16777216  (24bits)
	if ((ticks - 1UL) <= 0xFFFFFFUL){
		 /* set reload register */
		SysTick->LOAD  = (uint32_t)(ticks - 1UL);

		/* set Priority for Systick Interrupt */
		//NVIC_SetPriority (SysTick_IRQn, (1UL << __NVIC_PRIO_BITS) - 1UL);

		SysTick->VAL   = 0UL;			/* Load the SysTick Counter Value */

		SysTick->CTRL  = (0 << 2) |		/* 0 -> SysTick_Clock = AHB/8 */
						 (1 << 1) |	 	/* Enable SysTick IRQ and SysTick Timer */
						 (1 << 0);
	}

	int count = 0;
	while(1){
		if (SysTick_TASK){
			GPIOC->ODR &= ~((1 << 13) | (1 << 14) | (1 << 15));
			SysTick_TASK = 0;
			switch (count){
				case 0:
					break;
				case 1:
					GPIOC->ODR ^= (1 << 13);
					break;
				case 2:
					GPIOC->ODR ^= (1 << 14);
					break;
				case 3:
					GPIOC->ODR ^= (1 << 15);
					break;
				case 4:
					GPIOC->ODR ^= (1 << 13) | (1 << 14);
					break;
				case 5:
					GPIOC->ODR ^= (1 << 14) | (1 << 15);
					break;
				case 6:
					GPIOC->ODR ^= (1 << 13) | (1 << 15);
					break;
				case 7:
					GPIOC->ODR ^= (1 << 13) | (1 << 14) | (1 << 15);
				default:
					break;
			}
			count++;
			if (count > 7){
				count = 0;
			}
		}
	}
}
